
package job_portal;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class already_applied_job extends javax.swing.JFrame {

String applicant_id="";
String job_id;
String status="";
public Connection connection;
    public already_applied_job() {
        initComponents();
    }
    
    public already_applied_job(String applicant_id) {
        initComponents();
        this.applicant_id=applicant_id;
        show_user();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back_btn = new javax.swing.JButton();
        loc = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        status_label = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        already_applied_table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1094, 631));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back_btn.setBackground(new java.awt.Color(0, 0, 0));
        back_btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/undo.png"))); // NOI18N
        back_btn.setText("Back");
        back_btn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 580, 80, 40));

        loc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(loc, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 190, 30));

        msg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 190, 40));

        status_label.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jPanel1.add(status_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 310, 30));

        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 190, 30));

        already_applied_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job Category", "Job Posting", "Job type", "Job ID"
            }
        ));
        already_applied_table.setRowHeight(32);
        already_applied_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                already_applied_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(already_applied_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 500, 300));

        jLabel2.setFont(new java.awt.Font("TATU", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Already Applied For A Job?");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 640, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/development1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 1220, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String msg1,loc1,date1;
    private void already_applied_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_already_applied_tableMouseClicked
        // TODO add your handling code here:
        int i = already_applied_table.getSelectedRow();
        TableModel model =already_applied_table.getModel();
        job_id=model.getValueAt(i,3).toString();
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = java.sql.DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=job_portal;selectMethod=cursor", "sa", "123456");
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement
                    .executeQuery("select * from  job_result where applicant_id= "+applicant_id+" AND job_id ="+job_id);
            while (resultSet.next()) {
                status =resultSet.getString("status");
                
                msg1=resultSet.getString("short_message");
                loc1=resultSet.getString("interview_location");
                date1 =resultSet.getString("interview_date");
                System.out.println(""+status);
            }
            if(status.equals(""))
                {
                 status_label.setText("Result is not published Yet");
                }
               else if(status.equals("0"))
                {
                 status_label.setText("Sorry, You are Rejected");
                }
                else if(status.equals("1"))
                {
                 status_label.setText("Congratulation , You are Selected");
                 msg.setText(msg1);
                 loc.setText(loc1);
                 date.setText(date1);
                }
           
        } catch (Exception e) {
            e.printStackTrace();
        }
               
    }//GEN-LAST:event_already_applied_tableMouseClicked

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        
             after_job_seeker_login f1 = new after_job_seeker_login(applicant_id);
                f1.setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(already_applied_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(already_applied_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(already_applied_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(already_applied_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new already_applied_job().setVisible(true);
            }
        });
    }
     public ArrayList<already_applied_job_class> userList(){
        ArrayList<already_applied_job_class> usersList = new ArrayList<>();
         try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = java.sql.DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=job_portal;selectMethod=cursor", "sa", "123456");
            String query1="SELECT  application_details.job_id,Job_Information.job_category,Job_Information.job_posting,Job_Information.job_type FROM application_details  INNER JOIN Job_Information ON application_details.job_id = Job_Information.job_id WHERE application_details.applicant_id = "+applicant_id;
            Statement st1= connection.createStatement();
            ResultSet rs1= st1.executeQuery(query1);
            already_applied_job_class user;
            while(rs1.next()){
                user=new already_applied_job_class(rs1.getString("job_category"),rs1.getString("job_posting"),rs1.getString("job_type"),rs1.getString("job_id"));
                usersList.add(user);
            }
         }
         catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
         return usersList;
    }

    public void show_user(){
        ArrayList<already_applied_job_class> list = userList();
        DefaultTableModel model = (DefaultTableModel)already_applied_table.getModel();
        Object[] row = new Object[4];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getJob_category();
            row[1]=list.get(i).getJob_posting();
            row[2]=list.get(i).getJob_type();
            row[3]=list.get(i).getJob_id();
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable already_applied_table;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loc;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel status_label;
    // End of variables declaration//GEN-END:variables
}
