/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package job_portal;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Siham
 */

public class applicant_list extends javax.swing.JFrame {
String Job_ID,company_id;
String select_applicant;
int i=-1;
public Connection connection;
    /**
     * Creates new form applicant_list
     */
    public applicant_list() {
        initComponents();
        show_user();
    }
    public applicant_list(String JobID ) {
        initComponents();
        Job_ID=JobID;
        show_user();
        }
    public applicant_list(String JobID,String company_id ) {
        initComponents();
        Job_ID=JobID;
        this.company_id=company_id;
        show_user();
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        applicant_list = new javax.swing.JTable();
        view_applicant_details = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        applicant_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Applicant ID", "Payment Status", "Trx No", "Transection By", "Reason for hiring", "Skills", "Experience", "Status"
            }
        ));
        applicant_list.setRowHeight(32);
        applicant_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                applicant_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(applicant_list);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 740, 250));

        view_applicant_details.setBackground(new java.awt.Color(0, 0, 0));
        view_applicant_details.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        view_applicant_details.setForeground(new java.awt.Color(255, 255, 255));
        view_applicant_details.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/tap.png"))); // NOI18N
        view_applicant_details.setText("View Applicant Details");
        view_applicant_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_applicant_detailsActionPerformed(evt);
            }
        });
        jPanel1.add(view_applicant_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 210, 40));

        back_btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/undo.png"))); // NOI18N
        back_btn.setText("Back");
        back_btn.setBorder(new javax.swing.border.MatteBorder(null));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 600, 80, 40));

        jLabel2.setFont(new java.awt.Font("TATU", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText(" Details of Applicant");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 490, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/collar jobs.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-720, 0, 1800, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applicant_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applicant_listMouseClicked
        // TODO add your handling code here:
         i = applicant_list.getSelectedRow();
        TableModel model =applicant_list.getModel();
        select_applicant=model.getValueAt(i,0).toString();
    }//GEN-LAST:event_applicant_listMouseClicked

    private void view_applicant_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_applicant_detailsActionPerformed
        // TODO add your handling code here:
        if(i==-1)
        {
             JOptionPane.showMessageDialog(null, "Select  applicant First");
        }
        else{
                display_applicant_details f= new display_applicant_details(select_applicant,Job_ID,company_id);
             f.setVisible(true);
             setVisible(false);
        }
    }//GEN-LAST:event_view_applicant_detailsActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
            after_job_giver_login f= new after_job_giver_login(company_id);
             f.setVisible(true);
             setVisible(false);
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(applicant_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(applicant_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(applicant_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(applicant_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new applicant_list().setVisible(true);
            }
        });
    }
    public ArrayList<view_application_details_class> userList(){
        ArrayList<view_application_details_class> usersList = new ArrayList<>();
         try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = java.sql.DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=job_portal;selectMethod=cursor", "sa", "123456");
            String query1="SELECT application_details.emp_status,application_details.applicant_id , skills,experience,reason_for_hiring,status,trx_id,transection_by  FROM application_details  INNER JOIN transection ON application_details.applicant_id = transection.applicant_id AND application_details.job_id = transection.job_id WHERE application_details.job_id = "+Job_ID;
            Statement st1= connection.createStatement();
            ResultSet rs1= st1.executeQuery(query1);
            view_application_details_class user;
            while(rs1.next()){
                user=new view_application_details_class(rs1.getString("applicant_id"),rs1.getString("skills"),rs1.getString("experience"),
                rs1.getString("reason_for_hiring"),rs1.getString("status"),rs1.getString("trx_id"),rs1.getString("transection_by"),rs1.getString("emp_status")
                );
                usersList.add(user);
            }
         }
         catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
         return usersList;
    }

    public void show_user(){
        ArrayList<view_application_details_class> list = userList();
        DefaultTableModel model = (DefaultTableModel)applicant_list.getModel();
        Object[] row = new Object[8];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getApplicant_id();
            row[1]=list.get(i).getTrx_id();
            row[3]=list.get(i).getStatus();
            row[2]=list.get(i).getTransection_by();
            row[4]=list.get(i).getReason_for_hiring();
            row[5]=list.get(i).getSkills();
            row[6]=list.get(i).getExperience();
            row[7]=list.get(i).getEmp_status();
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable applicant_list;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton view_applicant_details;
    // End of variables declaration//GEN-END:variables
}
