/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package job_portal;

import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Siham
 */
public class job_seeker_sign_up extends javax.swing.JFrame {

    /**
     * Creates new form job_seeker_sign_up
     */
    int row=0;
    public job_seeker_sign_up() {
        initComponents();
         try{
         Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = java.sql.DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=job_portal;selectMethod=cursor", "sa", "123456");
             /*Finding ID*/  
             Statement statement = connection.createStatement();
            ResultSet resultSet = statement
                    .executeQuery("SELECT applicant_id FROM applicant");
            while (resultSet.next()) {    
                row++;
            }
            row+=1000;
            System.out.println(""+row);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        applicant_name = new javax.swing.JTextField();
        applicant_phone = new javax.swing.JTextField();
        applicant_email = new javax.swing.JTextField();
        applicant_present_adrs = new javax.swing.JTextField();
        applicant_permanent_adrs = new javax.swing.JTextField();
        applicant_male = new javax.swing.JRadioButton();
        applicant_female = new javax.swing.JRadioButton();
        applicant_same = new javax.swing.JCheckBox();
        applicant_password = new javax.swing.JPasswordField();
        applicant_create_acc = new javax.swing.JButton();
        applicant_image = new javax.swing.JLabel();
        choose_img = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ssc = new javax.swing.JRadioButton();
        hsc = new javax.swing.JRadioButton();
        hons = new javax.swing.JRadioButton();
        mas = new javax.swing.JRadioButton();
        back_btn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        dob_bar = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Name : ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 50, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Phone : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Email : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Date Of Birth : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Password : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Gender : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Present Address : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, -1, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("Permanent Address : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, 40));

        applicant_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicant_nameActionPerformed(evt);
            }
        });
        jPanel1.add(applicant_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 270, -1));
        jPanel1.add(applicant_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 270, -1));
        jPanel1.add(applicant_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 270, -1));
        jPanel1.add(applicant_present_adrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 270, 40));

        applicant_permanent_adrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicant_permanent_adrsActionPerformed(evt);
            }
        });
        jPanel1.add(applicant_permanent_adrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 270, 40));

        buttonGroup1.add(applicant_male);
        applicant_male.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        applicant_male.setForeground(new java.awt.Color(255, 255, 255));
        applicant_male.setText("Male");
        applicant_male.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(applicant_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 60, -1));

        buttonGroup1.add(applicant_female);
        applicant_female.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        applicant_female.setForeground(new java.awt.Color(255, 255, 255));
        applicant_female.setText("Female");
        applicant_female.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(applicant_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 80, -1));

        applicant_same.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        applicant_same.setForeground(new java.awt.Color(255, 255, 255));
        applicant_same.setText("Same as present address");
        applicant_same.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(applicant_same, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 160, 30));

        applicant_password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(applicant_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 270, -1));

        applicant_create_acc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        applicant_create_acc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/create.png"))); // NOI18N
        applicant_create_acc.setText("Create Account");
        applicant_create_acc.setBorder(new javax.swing.border.MatteBorder(null));
        applicant_create_acc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicant_create_accActionPerformed(evt);
            }
        });
        jPanel1.add(applicant_create_acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 160, 40));
        jPanel1.add(applicant_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 170, 130));

        choose_img.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        choose_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/photo.png"))); // NOI18N
        choose_img.setText("Choose photo");
        choose_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        choose_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose_imgActionPerformed(evt);
            }
        });
        jPanel1.add(choose_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 110, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("Education : ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, 20));

        buttonGroup2.add(ssc);
        ssc.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        ssc.setForeground(new java.awt.Color(255, 255, 255));
        ssc.setText("SSC");
        ssc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(ssc, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 50, 20));

        buttonGroup2.add(hsc);
        hsc.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        hsc.setForeground(new java.awt.Color(255, 255, 255));
        hsc.setText("HSC");
        jPanel1.add(hsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 50, -1));

        buttonGroup2.add(hons);
        hons.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        hons.setForeground(new java.awt.Color(255, 255, 255));
        hons.setText("Honors");
        jPanel1.add(hons, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 70, -1));

        buttonGroup2.add(mas);
        mas.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        mas.setForeground(new java.awt.Color(255, 255, 255));
        mas.setText("Masters");
        jPanel1.add(mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 70, -1));

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 650, -1, -1));

        jLabel11.setFont(new java.awt.Font("TATU", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 0));
        jLabel11.setText("       Register Here");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 460, 50));
        jPanel1.add(dob_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 270, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/down-arrow (1).png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 70, 80));

        jLabel13.setFont(new java.awt.Font("TATU", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 0));
        jLabel13.setText("  Join Us");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 140, 40));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("  For more exciting news and features ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 310, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("    visit our website...");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 180, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/information.png"))); // NOI18N
        jButton1.setText("About Us");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 170, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/blogin.jpg"))); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(1443, 880));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 4, 1000, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applicant_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicant_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_applicant_nameActionPerformed

      public Connection connection;
      String filename=null;
      byte[] img=null;
    private void applicant_create_accActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicant_create_accActionPerformed
        // TODO add your handling code here:
     /*  */
          try{
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = java.sql.DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=job_portal;selectMethod=cursor", "sa", "123456");
            String query = "INSERT INTO applicant(applicant_name, applicant_phone,applicant_email, date_of_birth,applicant_age,image,gender,present_address,permanent_address,password,education) values(?,?,?,?,?,?,?,?,?,?,?)";
            String gen="";
            String edu = "";
            String permanent,present;
            if(ssc.isSelected())
            {
            edu = "SSC";
            }
            else if(hsc.isSelected())
            {
            edu = "HSC";
            }
            else if(hons.isSelected())
            {
            edu = "Honors";
            }
            else if(mas.isSelected())
            {
            edu = "Masters";
            }
            if(applicant_male.isSelected()){
                gen="Male";
            }
            if(applicant_female.isSelected()){
                gen="Female";
            }
            permanent=applicant_permanent_adrs.getText();
            present=applicant_present_adrs.getText();
             if(applicant_same.isSelected()){  
                permanent = present;
            }
            //String dob= dob_bar.getDateFormatString();
            Calendar dob = dob_bar.getCalendar();
             int yr=dob.get(Calendar.YEAR);
             int mon=dob.get(Calendar.MONTH);
             int day =dob.get(Calendar.DAY_OF_MONTH);
             String date_of=day+"/"+mon+"/"+yr;
             int age = age_calc(dob);
           /*  System.out.println(""+age);
             System.out.println(""+date_of);*/
               
            PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1, applicant_name.getText());
            pst.setString(2, applicant_phone.getText());
            pst.setString(3, applicant_email.getText());
            pst.setString(4, date_of);
            pst.setString(5, Integer.toString(age));
            pst.setBytes(6, img);
            pst.setString(7, gen);
            pst.setString(8, present);
            pst.setString(9, permanent);
            pst.setString(10, applicant_password.getText());
            pst.setString(11, edu);
        
            boolean valid_p=chk_phn(applicant_phone.getText());
            boolean valid_m=chk_mail(applicant_email.getText());
            if(!valid_p)
            {
             JOptionPane.showMessageDialog(null,"Invalid Phone Number");
            }
            else if(!valid_m)
            {
             JOptionPane.showMessageDialog(null,"Invalid Email");
            }
            else
            {
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "account created successfully!\n Your ID ="+(row+1)+"\n\nRemember ID for the next login\n\n");
             after_job_seeker_login f1 = new after_job_seeker_login(""+(row+1));
                f1.setVisible(true);
                setVisible(false);
            }
        }
         catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_applicant_create_accActionPerformed

    private void choose_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose_imgActionPerformed
        // TODO add your handling code here:
       JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        ImageIcon imageicon=new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(applicant_image.getWidth(), applicant_image.getHeight(), Image.SCALE_SMOOTH));
        applicant_image.setIcon(imageicon);
        try{
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum; (readNum = fis.read(buf))!=-1;) {
                bos.write(buf,0,readNum);
            }
            img=bos.toByteArray();
        }catch(Exception e)
        { }
    }//GEN-LAST:event_choose_imgActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
         login_as_job_seeker f= new login_as_job_seeker();
             f.setVisible(true);
             setVisible(false);
    }//GEN-LAST:event_back_btnActionPerformed

    private void applicant_permanent_adrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicant_permanent_adrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_applicant_permanent_adrsActionPerformed
public boolean chk_phn(String phn)
{
boolean valid = false;
if(phn.length()==11 && (phn.startsWith("017") || phn.startsWith("016") || phn.startsWith("019") || phn.startsWith("018") || phn.startsWith("015")))
{
    valid=true;
}
return valid;
}

public boolean chk_mail(String mail)
{
boolean valid_mail= false;
if(mail.endsWith("@yahoo.com") || mail.endsWith("@gmail.com"))
{
    valid_mail=true;
}
return valid_mail;
}

    public int age_calc(Calendar dob)
{
Calendar now = Calendar.getInstance();
if (dob.after(now)) {
 // throw new IllegalArgumentException("Can't be born in the future");
  JOptionPane.showMessageDialog(null, "Can't be born in the future");
}
int year1 = now.get(Calendar.YEAR);
int year2 = dob.get(Calendar.YEAR);
int age = year1 - year2;
int month1 = now.get(Calendar.MONTH);
int month2 = dob.get(Calendar.MONTH);
if (month2 > month1) {
  age--;
} else if (month1 == month2) {
  int day1 = now.get(Calendar.DAY_OF_MONTH);
  int day2 = dob.get(Calendar.DAY_OF_MONTH);
  if (day2 > day1) {
    age--;
  }
}
return age;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(job_seeker_sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(job_seeker_sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(job_seeker_sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(job_seeker_sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new job_seeker_sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applicant_create_acc;
    private javax.swing.JTextField applicant_email;
    private javax.swing.JRadioButton applicant_female;
    private javax.swing.JLabel applicant_image;
    private javax.swing.JRadioButton applicant_male;
    private javax.swing.JTextField applicant_name;
    private javax.swing.JPasswordField applicant_password;
    private javax.swing.JTextField applicant_permanent_adrs;
    private javax.swing.JTextField applicant_phone;
    private javax.swing.JTextField applicant_present_adrs;
    private javax.swing.JCheckBox applicant_same;
    private javax.swing.JButton back_btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton choose_img;
    private com.toedter.calendar.JDateChooser dob_bar;
    private javax.swing.JRadioButton hons;
    private javax.swing.JRadioButton hsc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton mas;
    private javax.swing.JRadioButton ssc;
    // End of variables declaration//GEN-END:variables
}
