/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package job_portal;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Siham
 */
public class login_as_job_giver extends javax.swing.JFrame {

    /**
     * Creates new form login_as_job_giver
     */
    public login_as_job_giver() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ab = new javax.swing.JLabel();
        CompanyId = new javax.swing.JTextField();
        loginJobGiver = new javax.swing.JButton();
        JobGiverNewAccount = new javax.swing.JButton();
        ab1 = new javax.swing.JLabel();
        CompanyPassword = new javax.swing.JPasswordField();
        ResetJobGiver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back_btn.setBackground(new java.awt.Color(0, 0, 0));
        back_btn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/undo.png"))); // NOI18N
        back_btn.setText("Back");
        back_btn.setBorder(new javax.swing.border.MatteBorder(null));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 575, 90, 40));

        jLabel2.setFont(new java.awt.Font("TATU", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("   Hello!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 130, 40));

        jLabel3.setFont(new java.awt.Font("TATU", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/arrow-right.png"))); // NOI18N
        jLabel3.setText("Sign in to your account");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 390, 60));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ab.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        ab.setForeground(new java.awt.Color(51, 51, 51));
        ab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/ID.png"))); // NOI18N
        ab.setText("Company ID :");
        jPanel2.add(ab, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 50, 110, 30));

        CompanyId.setBackground(new java.awt.Color(153, 153, 153));
        CompanyId.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CompanyId.setForeground(new java.awt.Color(255, 255, 255));
        CompanyId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 0)));
        CompanyId.setCaretColor(new java.awt.Color(255, 153, 0));
        jPanel2.add(CompanyId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 46, 170, 30));

        loginJobGiver.setBackground(new java.awt.Color(0, 0, 0));
        loginJobGiver.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        loginJobGiver.setForeground(new java.awt.Color(255, 153, 0));
        loginJobGiver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/login.png"))); // NOI18N
        loginJobGiver.setText("Log in");
        loginJobGiver.setBorder(new javax.swing.border.MatteBorder(null));
        loginJobGiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJobGiverActionPerformed(evt);
            }
        });
        jPanel2.add(loginJobGiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 80, 30));

        JobGiverNewAccount.setBackground(new java.awt.Color(0, 0, 0));
        JobGiverNewAccount.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JobGiverNewAccount.setForeground(new java.awt.Color(255, 153, 0));
        JobGiverNewAccount.setText("Don't have an account?Create Here");
        JobGiverNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JobGiverNewAccountActionPerformed(evt);
            }
        });
        jPanel2.add(JobGiverNewAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        ab1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        ab1.setForeground(new java.awt.Color(51, 51, 51));
        ab1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/padlock.png"))); // NOI18N
        ab1.setText("Password : ");
        jPanel2.add(ab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 90, 110, 30));

        CompanyPassword.setBackground(new java.awt.Color(153, 153, 153));
        CompanyPassword.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CompanyPassword.setForeground(new java.awt.Color(255, 255, 255));
        CompanyPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 0)));
        CompanyPassword.setCaretColor(new java.awt.Color(255, 153, 0));
        jPanel2.add(CompanyPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 170, 30));

        ResetJobGiver.setBackground(new java.awt.Color(0, 0, 0));
        ResetJobGiver.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ResetJobGiver.setForeground(new java.awt.Color(255, 153, 0));
        ResetJobGiver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/Reset.png"))); // NOI18N
        ResetJobGiver.setText("Reset");
        ResetJobGiver.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(ResetJobGiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 80, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 430, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/giver.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -5, 1000, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public Connection connection;
    private void loginJobGiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJobGiverActionPerformed
try{
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = java.sql.DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=job_portal;selectMethod=cursor", "sa", "123456");
            String sql = "Select * from company where  company_id = ? and password = ?";
            PreparedStatement pst = connection.prepareStatement(sql);
            pst.setString(1, CompanyId.getText());
            pst.setString(2, CompanyPassword.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "ID and Password Matched");
                after_job_giver_login f1 = new after_job_giver_login(CompanyId.getText());
                f1.setVisible(true);
                setVisible(false);
                /*Succes field= new Succes();
                field.setVisible(true);
                setVisible(false);*/
             
            }
            else{
                JOptionPane.showMessageDialog(null, "ID and password not Correct");
                /*username.setText("");
                password.setText("");*/
            }
            connection.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_loginJobGiverActionPerformed

    private void JobGiverNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JobGiverNewAccountActionPerformed
        job_giver_sign_up f = new job_giver_sign_up();
        f.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_JobGiverNewAccountActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        login_selection f= new login_selection();
             f.setVisible(true);
             setVisible(false);
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_as_job_giver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_as_job_giver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_as_job_giver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_as_job_giver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_as_job_giver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CompanyId;
    private javax.swing.JPasswordField CompanyPassword;
    private javax.swing.JButton JobGiverNewAccount;
    private javax.swing.JButton ResetJobGiver;
    private javax.swing.JLabel ab;
    private javax.swing.JLabel ab1;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginJobGiver;
    // End of variables declaration//GEN-END:variables
}
