/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package job_portal;

import java.awt.Color;
import static java.awt.PageAttributes.ColorType.COLOR;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Siham
 */
public class login_selection extends javax.swing.JFrame {

    /**
     * Creates new form login_selection
     */
    public login_selection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login_as_job_giver = new javax.swing.JButton();
        login_as_job_seeker = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_as_job_giver.setBackground(new java.awt.Color(0, 0, 0));
        login_as_job_giver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        login_as_job_giver.setForeground(new java.awt.Color(255, 255, 255));
        login_as_job_giver.setText("Login as Job giver");
        login_as_job_giver.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        login_as_job_giver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_as_job_giverActionPerformed(evt);
            }
        });
        jPanel1.add(login_as_job_giver, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 180, 210, 50));

        login_as_job_seeker.setBackground(new java.awt.Color(0, 0, 0));
        login_as_job_seeker.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        login_as_job_seeker.setForeground(new java.awt.Color(255, 255, 255));
        login_as_job_seeker.setText("Login as Job seeker");
        login_as_job_seeker.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        login_as_job_seeker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_as_job_seekerActionPerformed(evt);
            }
        });
        jPanel1.add(login_as_job_seeker, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 110, 210, 50));

        jLabel2.setFont(new java.awt.Font("TATU", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Choose Your Career To Continue...");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 540, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/businessman (1).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 70, 60));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Exit");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 90, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/details.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 700, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_as_job_seekerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_as_job_seekerActionPerformed
        // TODO add your handling code here:
        
        login_as_job_seeker f1 = new login_as_job_seeker();
        f1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_login_as_job_seekerActionPerformed

    private void login_as_job_giverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_as_job_giverActionPerformed
        // TODO add your handling code here:
        login_as_job_giver f2 = new login_as_job_giver();
        f2.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_login_as_job_giverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int a=JOptionPane.showConfirmDialog(null, "Do you really want to Close Application","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
            System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_selection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login_as_job_giver;
    private javax.swing.JButton login_as_job_seeker;
    // End of variables declaration//GEN-END:variables
}
