/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package job_portal;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author Siham
 */
public class login_as_job_seeker extends javax.swing.JFrame {

    /**
     * Creates new form login_as_job_seeker
     */
    public login_as_job_seeker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ResetJobSeeker = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        loginJobSeeker = new javax.swing.JButton();
        applicantPassword = new javax.swing.JPasswordField();
        JobSeekerNewAccount = new javax.swing.JButton();
        applicantId = new javax.swing.JTextField();
        back_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(604, 380));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/padlock.png"))); // NOI18N
        jLabel2.setText("Password : ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 120, 40));

        ResetJobSeeker.setBackground(new java.awt.Color(255, 102, 102));
        ResetJobSeeker.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ResetJobSeeker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/Reset.png"))); // NOI18N
        ResetJobSeeker.setText("Reset");
        ResetJobSeeker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetJobSeekerActionPerformed(evt);
            }
        });
        jPanel2.add(ResetJobSeeker, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 100, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/ID.png"))); // NOI18N
        jLabel1.setText("Applicant ID :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 120, 40));

        loginJobSeeker.setBackground(new java.awt.Color(0, 204, 0));
        loginJobSeeker.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        loginJobSeeker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/login.png"))); // NOI18N
        loginJobSeeker.setText("Log in");
        loginJobSeeker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJobSeekerActionPerformed(evt);
            }
        });
        jPanel2.add(loginJobSeeker, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 100, 30));

        applicantPassword.setBackground(new java.awt.Color(153, 204, 255));
        applicantPassword.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        applicantPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 0)));
        applicantPassword.setCaretColor(new java.awt.Color(255, 153, 0));
        jPanel2.add(applicantPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 190, 30));

        JobSeekerNewAccount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JobSeekerNewAccount.setForeground(new java.awt.Color(255, 153, 0));
        JobSeekerNewAccount.setText("Don't have an account?Create Here");
        JobSeekerNewAccount.setBorder(new javax.swing.border.MatteBorder(null));
        JobSeekerNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JobSeekerNewAccountActionPerformed(evt);
            }
        });
        jPanel2.add(JobSeekerNewAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 280, 40));

        applicantId.setBackground(new java.awt.Color(153, 204, 255));
        applicantId.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        applicantId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 0)));
        applicantId.setCaretColor(new java.awt.Color(255, 153, 0));
        jPanel2.add(applicantId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 190, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 390, 250));

        back_btn.setBackground(new java.awt.Color(0, 0, 0));
        back_btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/undo.png"))); // NOI18N
        back_btn.setText("Back");
        back_btn.setBorder(new javax.swing.border.MatteBorder(null));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 90, -1));

        jLabel4.setFont(new java.awt.Font("TATU", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("     Hello!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 140, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/arrow-right.png"))); // NOI18N
        jLabel5.setText("Sign in to your account");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 230, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/login-page-background.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 600, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public Connection connection;
    private void loginJobSeekerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJobSeekerActionPerformed
       try{
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = java.sql.DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=job_portal;selectMethod=cursor", "sa", "123456");
            String sql = "Select * from applicant where applicant_id = ? and password = ?";
            PreparedStatement pst = connection.prepareStatement(sql);
            pst.setString(1, applicantId.getText());
            pst.setString(2, applicantPassword.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "ID and Password Matched");
                after_job_seeker_login f2 = new after_job_seeker_login(applicantId.getText());
                f2.setVisible(true);
                setVisible(false);
                /*Succes field= new Succes();
                field.setVisible(true);
                setVisible(false);*/
             
            }
            else{
                JOptionPane.showMessageDialog(null, "ID and password not Correct");
                /*username.setText("");
                password.setText("");*/
            }
            connection.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_loginJobSeekerActionPerformed

    private void ResetJobSeekerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetJobSeekerActionPerformed
        // TODO add your handling code here:
        applicantId.setText("");
       applicantPassword.setText("");
    }//GEN-LAST:event_ResetJobSeekerActionPerformed

    private void JobSeekerNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JobSeekerNewAccountActionPerformed
        // TODO add your handling code here:
        job_seeker_sign_up f1 = new job_seeker_sign_up();
        f1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_JobSeekerNewAccountActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
         login_selection f= new login_selection();
             f.setVisible(true);
             setVisible(false);
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_as_job_seeker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_as_job_seeker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_as_job_seeker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_as_job_seeker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_as_job_seeker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JobSeekerNewAccount;
    private javax.swing.JButton ResetJobSeeker;
    private javax.swing.JTextField applicantId;
    private javax.swing.JPasswordField applicantPassword;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginJobSeeker;
    // End of variables declaration//GEN-END:variables
}
