/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package job_portal;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Siham
 */
public class post_a_job extends javax.swing.JFrame {

    /**
     * Creates new form post_a_job
     */
    String company_id;
    public post_a_job() {
        initComponents();
    }
    public post_a_job(String company_id) {
        initComponents();
        this.company_id=company_id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        job_catagory = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        job_fulltime = new javax.swing.JRadioButton();
        job_parttime = new javax.swing.JRadioButton();
        job_vacancy = new javax.swing.JTextField();
        job_salary = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        job_age = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        job_req = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        job_fee = new javax.swing.JTextField();
        job_loc = new javax.swing.JComboBox<>();
        post_btn = new javax.swing.JButton();
        last_date = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Job Catagory:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, -1, -1));

        job_catagory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accounting", "Bank", "Education", "Engineer", "HR", "IT", "Marketing", "Others" }));
        jPanel1.add(job_catagory, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText(" Requirements : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, -1, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Employment Status : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, -1, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Vacancy : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, -1, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Salary Range : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, -1, 20));

        buttonGroup1.add(job_fulltime);
        job_fulltime.setText("Full Time");
        jPanel1.add(job_fulltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, -1, -1));

        buttonGroup1.add(job_parttime);
        job_parttime.setText("Part Time");
        jPanel1.add(job_parttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 300, -1, -1));
        jPanel1.add(job_vacancy, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, 160, -1));
        jPanel1.add(job_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 500, 160, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Age Range:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, -1, 20));
        jPanel1.add(job_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, 160, -1));

        job_req.setColumns(20);
        job_req.setRows(5);
        jScrollPane1.setViewportView(job_req);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, 190, 80));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Form fee : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("Job Location : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, -1, 20));

        job_fee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                job_feeActionPerformed(evt);
            }
        });
        jPanel1.add(job_fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 160, -1));

        job_loc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka", "Barisal", "Chittagong ", "Khulna ", "Mymensingh", "Rajshahi", "Sylhet", "Rangpur" }));
        jPanel1.add(job_loc, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 460, -1, -1));

        post_btn.setBackground(new java.awt.Color(0, 0, 0));
        post_btn.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        post_btn.setForeground(new java.awt.Color(255, 153, 0));
        post_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/job.png"))); // NOI18N
        post_btn.setText("Post Job");
        post_btn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        post_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                post_btnActionPerformed(evt);
            }
        });
        jPanel1.add(post_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 595, 110, 40));
        jPanel1.add(last_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, 160, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("Application last date:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, -1, -1));

        cancel.setBackground(new java.awt.Color(0, 0, 0));
        cancel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/Close.png"))); // NOI18N
        cancel.setText("Cancel");
        cancel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 595, 120, 40));

        jLabel11.setFont(new java.awt.Font("TATU", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 0));
        jLabel11.setText("  Job Posting Information");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 390, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/job recruitment.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public Connection connection;
    private void post_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_post_btnActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = java.sql.DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=job_portal;selectMethod=cursor", "sa", "123456");
            String query = "INSERT INTO Job_Information(company_id, application_LastDate,job_category, job_requirements,job_type,No_of_vacancy,salary,form_fee,age,job_posting) values(?,?,?,?,?,?,?,?,?,?)";
            
            String job_category=job_catagory.getSelectedItem().toString();
            String requirements= job_req.getText();
            String job_type=null;
            if(job_parttime.isSelected()){
              job_type= "Part Time";
            } 
            else
            {
              job_type= "Full Time";
            }
            String vacancy = job_vacancy.getText();
            String salary =job_salary.getText();
            String age = job_age.getText();
            String fee= job_fee.getText();
            String loc =job_loc.getSelectedItem().toString();
            
            Calendar dob = last_date.getCalendar();
             int yr=dob.get(Calendar.YEAR);
             int mon=dob.get(Calendar.MONTH)+1;
             int day =dob.get(Calendar.DAY_OF_MONTH);
             String lastdate=day+"/"+mon+"/"+yr;
             
             /*save into database*/
             PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1,company_id );
            pst.setString(2,lastdate );
            pst.setString(3,job_category );
            pst.setString(4,requirements);
            pst.setString(5,job_type);
            pst.setString(6,vacancy);
            pst.setString(7,salary );
            pst.setString(8,fee );
            pst.setString(9,age );
            pst.setString(10,loc);
           pst.executeUpdate();
         
            JOptionPane.showMessageDialog(null, "Inserted Sucessfully!");
            after_job_giver_login f3=new after_job_giver_login(company_id);
            f3.setVisible(true);
            setVisible(false);
        }
         catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }
    }//GEN-LAST:event_post_btnActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        after_job_giver_login f=new after_job_giver_login(company_id);
        f.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void job_feeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_job_feeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_job_feeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(post_a_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(post_a_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(post_a_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(post_a_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new post_a_job().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField job_age;
    private javax.swing.JComboBox<String> job_catagory;
    private javax.swing.JTextField job_fee;
    private javax.swing.JRadioButton job_fulltime;
    private javax.swing.JComboBox<String> job_loc;
    private javax.swing.JRadioButton job_parttime;
    private javax.swing.JTextArea job_req;
    private javax.swing.JTextField job_salary;
    private javax.swing.JTextField job_vacancy;
    private com.toedter.calendar.JDateChooser last_date;
    private javax.swing.JButton post_btn;
    // End of variables declaration//GEN-END:variables
}
