/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package job_portal;

import java.awt.EventQueue;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.List;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Collections;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;

/**
 *
 * @author Siham
 */
public class review_employee extends javax.swing.JFrame {

    /**
     * Creates new form review_employee
     */
    public review_employee() {
        initComponents();
        load_mail();
        autoSuggest();
    }
    private final Vector<String> v  = new Vector<String>();
    private JTextField tf;
    private boolean hide_flag = false;
    public Connection connection;
    int i = 0 ;
    String [] email ;
    
    void load_mail(){
    
    try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = java.sql.DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=job_portal;selectMethod=cursor", "sa", "123456");
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement
                    .executeQuery("SELECT * FROM applicant");
            while (resultSet.next()) {
                email[i]=resultSet.getString("applicant_email");
               i++;
            }
           
        }catch (Exception e) {
            e.printStackTrace();
        }
   /* for(Iterator<String> iterator = v.iterator();iterator.hasNext();){
    String next = iterator.next();
    }*/
        for (int j = 0; j < email.length; j++) {
            v.addElement(email[j]);
        }
    }
    private void setModel(DefaultComboBoxModel md1,String str)
    {
    combo.setModel(md1);
    combo.setSelectedIndex(-1);
    tf.setText(str);
    }
    
    private static DefaultComboBoxModel getSuggestedModel(List<String> list,String text){
        DefaultComboBoxModel m  = new DefaultComboBoxModel();
        for (String s : list) {
            if(s.startsWith(text)){
            m.addElement((s));
            }
        }
        return m;
    }

    void autoSuggest(){
    combo.setEditable(true);
    tf = (JTextField) combo.getEditor().getEditorComponent();
    
    tf.addKeyListener(new KeyListener() {
        @Override
        public void keyTyped(KeyEvent ke) {
             EventQueue.invokeLater(new Runnable() {
                 @Override
                 public void run() {
                     String text = tf.getText();
                     if(text.length() == 0){
                     combo.hidePopup();
                     setModel(new DefaultComboBoxModel(v),text);
                     }
                    else{
                     DefaultComboBoxModel m =getSuggestedModel(v,text);
                     if(m.getSize() ==0 || hide_flag){
                      combo.hidePopup();
                      hide_flag= false;
                     }
                     else
                      {
                      setModel(m,text);
                      combo.showPopup();
                      }
                     }
                 }
             });
        }

        @Override
        public void keyPressed(KeyEvent ke) {
           String text = tf.getText();
           int code = ke.getKeyCode();
           
           if(code== KeyEvent.VK_ENTER ){
           if(v.contains(text)){
           v.addElement(text);
           Collections.sort(v);
           setModel(getSuggestedModel(v,text),text);
           }
           hide_flag= true;
           }else if(code == KeyEvent.VK_ESCAPE){
           hide_flag= true;
           }else if(code == KeyEvent.VK_RIGHT){
               for (int j = 0; j < v.size(); j++) {
                  String str = v.elementAt(j);
                  if(str.startsWith(text))
                    {
                    combo.setSelectedIndex(-1);
                    tf.setText(str);
                    return;
                    }
               }
           }
        }

        @Override
        public void keyReleased(KeyEvent ke) {
            
        }
    });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        combo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(463, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(review_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(review_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(review_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(review_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new review_employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
