/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package job_portal;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Siham
 */
public class selected_for_job extends javax.swing.JFrame {
public Connection connection;
String job_id,applicant_id;
    /**
     * Creates new form selected_for_job
     */
    public selected_for_job() {
        initComponents();
    }
     public selected_for_job(String job_id,String applicant_id) {
        initComponents();
        this.job_id=job_id;
        this.applicant_id=applicant_id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        int_date = new com.toedter.calendar.JDateChooser();
        short_msg = new javax.swing.JTextField();
        interview_loc = new javax.swing.JTextField();
        ok_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 504));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Short Massage : ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Interview Location : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Interview Date : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));
        jPanel1.add(int_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 180, -1));
        jPanel1.add(short_msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 170, -1));
        jPanel1.add(interview_loc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 160, -1));

        ok_btn.setBackground(new java.awt.Color(0, 0, 0));
        ok_btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ok_btn.setForeground(new java.awt.Color(255, 255, 255));
        ok_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/tap.png"))); // NOI18N
        ok_btn.setText("OK");
        ok_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        ok_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_btnActionPerformed(evt);
            }
        });
        jPanel1.add(ok_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 223, 80, 40));

        cancel_btn.setBackground(new java.awt.Color(0, 0, 0));
        cancel_btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cancel_btn.setForeground(new java.awt.Color(255, 255, 255));
        cancel_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/Close.png"))); // NOI18N
        cancel_btn.setText("Cancel");
        cancel_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        jPanel1.add(cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 223, 80, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job_portal/notepad.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ok_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_btnActionPerformed
        // TODO add your handling code here:
        try{
         Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = java.sql.DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=job_portal;selectMethod=cursor", "sa", "123456");
            String query = "INSERT INTO job_result(job_id,applicant_id, status,short_message, interview_location,interview_date) values(?,?,?,?,?,?)";
             Calendar dob = int_date.getCalendar();
                int yr=dob.get(Calendar.YEAR);
                int mon=dob.get(Calendar.MONTH);
                int day =dob.get(Calendar.DAY_OF_MONTH);
                String date_of=day+"/"+mon+"/"+yr;
            PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1, job_id);
            pst.setString(2, applicant_id);
            pst.setString(3, "1");
            pst.setString(4, short_msg.getText());
            pst.setString(5, interview_loc.getText());
            pst.setString(6, date_of);
            
            pst.executeUpdate();
            
            /* Statement statement1 = connection.createStatement();
            String query1 = "delete FROM application_details where applicant_id= "+applicant_id +"AND job_id = "+job_id;
            PreparedStatement pst1 = connection.prepareStatement(query1);
            pst1.executeUpdate();*/
            
            String query1 = "UPDATE application_details set emp_status = ?  where applicant_id= "+applicant_id ;
            PreparedStatement pst1 = connection.prepareStatement(query1);
            pst1.setString(1, "Selected");
            pst1.executeUpdate();
            
               applicant_list f= new applicant_list(job_id);
             f.setVisible(true);
             setVisible(false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
             
    }//GEN-LAST:event_ok_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        // TODO add your handling code here:
         applicant_list f= new applicant_list(job_id);
             f.setVisible(true);
             setVisible(false);
    }//GEN-LAST:event_cancel_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selected_for_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selected_for_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selected_for_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selected_for_job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selected_for_job().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_btn;
    private com.toedter.calendar.JDateChooser int_date;
    private javax.swing.JTextField interview_loc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ok_btn;
    private javax.swing.JTextField short_msg;
    // End of variables declaration//GEN-END:variables
}
